zeno-ml/zeno-hub

DEVELOPMENT.md, backend/Dockerfile, buildspec.yml, frontend/Dockerfile
This PR adds:
1. `Dockerfile`s to build the frontend and backend
2. A buildspec.yml file that can be used for specifying build behavior for AWS
=> Add files for docker container building

backend/zeno_backend/classes/base.py, backend/zeno_backend/database/select.py, backend/zeno_backend/server.py, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/components/project/ProjectStat.svelte, frontend/src/lib/util/util.ts, frontend/src/lib/zenoapi/index.ts, frontend/src/lib/zenoapi/models/Project.ts, frontend/src/lib/zenoapi/models/ProjectStats.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/+page.svelte
=> feat: add project stats to project overview

frontend/src/lib/util/util.ts, frontend/vite.config.ts
Fetch in client-side components wasn't working in the docker setup.
=> fix: local fetch in docker

frontend/src/lib/util/util.ts, frontend/vite.config.ts
Reverts Sparkier/zeno_hub#105
I think this needs more testing before we merge. There are some issues with both the local and the docker setup.
=> Revert "fix: local fetch in docker"

backend/zeno_backend/classes/table.py, backend/zeno_backend/database/select.py, backend/zeno_backend/server.py, frontend/src/lib/components/chart/ChartHomeBlock.svelte, frontend/src/lib/components/chart/chart-page/chart-header/EditHeader.svelte, frontend/src/lib/components/chart/chart-page/chart-header/ViewHeader.svelte, frontend/src/lib/components/chart/chart-page/encoding/Encoding.svelte, frontend/src/lib/components/chart/chart-page/view-selection/ViewSelection.svelte, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/instance-views/TableView.svelte, frontend/src/lib/components/metadata/cells/FolderCell.svelte, frontend/src/lib/components/metadata/cells/TagCell.svelte, frontend/src/lib/components/settings/OrganizationsTable.svelte, frontend/src/routes/(app)/+page.svelte, frontend/src/routes/(app)/account/+page.svelte, frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte, frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte
Update some chart home styling and fix sorting for table view.
=> fix: chart styling, table sorting

backend/zeno_backend/database/select.py, frontend/src/lib/components/popups/SliceFinderPopup.svelte
Typo in slicefinder was re-writing the dataType
=> fix: small slicefinder issue

backend/zeno_backend/database/select.py, backend/zeno_backend/server.py, frontend/src/lib/components/metadata/SliceHeader.svelte, frontend/src/routes/+error.svelte, zeno_api/zeno_api/__init__.py
Small database issue fix, and make public the default.
=> fix: small database issue, public default projects

frontend/src/lib/components/chart/ChartContainer.svelte, frontend/src/lib/components/chart/ChartHomeBlock.svelte, frontend/src/lib/components/chart/chart-page/chart-header/EditHeader.svelte, frontend/src/lib/components/chart/chart-page/chart-header/HomeButton.svelte, frontend/src/lib/components/chart/chart-page/chart-header/ViewHeader.svelte, frontend/src/lib/components/instance-views/ComparisonView.svelte, frontend/src/lib/components/instance-views/ComparisonViewTableHeader.svelte, frontend/src/lib/components/instance-views/InstanceView.svelte, frontend/src/lib/components/instance-views/ListView.svelte, frontend/src/lib/components/instance-views/TableView.svelte, frontend/src/lib/components/instance-views/views/views/AudioTranscription.svelte, frontend/src/lib/components/metadata/MetadataHeader.svelte, frontend/src/lib/components/metadata/MetadataPanel.svelte, frontend/src/lib/components/metadata/SelectionBar.svelte, frontend/src/lib/components/metadata/Slices.svelte, frontend/src/lib/components/metadata/Tags.svelte, frontend/src/lib/components/popups/FilterEntry.svelte, frontend/src/lib/components/popups/FilterGroupEntry.svelte, frontend/src/lib/components/popups/Popup.svelte, frontend/src/lib/components/popups/SlicePopup.svelte, frontend/src/lib/stores.ts, frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte, frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte
Fixes various issues such as chart updates, comparison columns, styling issues.
=> fix: various style and functionality updates

backend/zeno_backend/database/select.py, backend/zeno_backend/database/util.py, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/general/HeaderIcon.svelte, frontend/src/lib/components/instance-views/ListView.svelte, frontend/src/lib/components/instance-views/TableView.svelte, frontend/src/lib/components/metadata/ChipsWrapper.svelte, frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/components/metadata/MetadataHeader.svelte, frontend/src/lib/components/metadata/SliceHeader.svelte, frontend/src/lib/components/metadata/Tags.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/SearchOption.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/TextMetadataCell.svelte, frontend/src/lib/components/popups/FilterEntry.svelte, frontend/src/lib/components/popups/Popup.svelte, frontend/src/lib/components/popups/SliceFinderPopup.svelte, frontend/src/lib/components/settings/OrganizationsTable.svelte
Minor usability issues, show text filtering.
=> fix: text metadata visualizations, usability issues

backend/zeno_backend/processing/chart.py, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/SlicesEncodingDropdown.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/SlicesEncodingMultiChoice.svelte, frontend/src/lib/components/chart/chart-types/table/TableRow.svelte
Always have a default "all instances" slice in charts.
=> feat: add overall slice option to charts

backend/zeno_backend/database/select.py, backend/zeno_backend/processing/chart.py, backend/zeno_backend/processing/histogram_processing.py, backend/zeno_backend/processing/metrics/__init__.py, backend/zeno_backend/processing/metrics/bleu.py, backend/zeno_backend/processing/metrics/f1.py, backend/zeno_backend/processing/metrics/map.py, backend/zeno_backend/processing/metrics/mean.py, backend/zeno_backend/server.py
Adds BLEU score to the backend and creates a new folder for metric calculation files.
Fixes [ZEN-100 : implement BLEU score](https://linear.app/zenoml/issue/ZEN-100/implement-bleu-score)
=> feat: refactor metrics folder and add BLEU score

backend/poetry.lock, backend/pyproject.toml, backend/zeno_backend/classes/filter.py, backend/zeno_backend/classes/metadata.py, backend/zeno_backend/database/select.py, backend/zeno_backend/processing/filtering.py, backend/zeno_backend/server.py, frontend/src/lib/components/metadata/cells/metadata-cells/TextMetadataCell.svelte, frontend/src/lib/components/popups/FilterEntry.svelte, frontend/src/lib/util/util.ts, frontend/src/lib/zenoapi/models/Operation.ts, frontend/src/lib/zenoapi/models/StringFilterRequest.ts, frontend/src/lib/zenoapi/services/ZenoService.ts
Simplify to regex or case sensitivity.
=> fix: make string filtering work

backend/zeno_backend/classes/metadata.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/util.py, backend/zeno_backend/processing/filtering.py, backend/zeno_backend/processing/histogram_processing.py, backend/zeno_backend/processing/metrics/mean.py, backend/zeno_backend/server.py, frontend/src/lib/api/metadata.ts, frontend/src/lib/components/chart/ChartHomeBlock.svelte, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/components/metadata/HistogramsHeader.svelte, frontend/src/lib/components/metadata/cells/MetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/BinaryMetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/NominalMetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/vegaSpecs.ts, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/stores.ts, frontend/src/lib/util/util.ts, frontend/src/lib/zenoapi/models/HistogramBucket.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/+page.server.ts, frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.server.ts, frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte
Simplify histogram generation, only one function to generate buckets and another to calculate counts & metrics.
=> refactor: fix histogram processing

backend/zeno_backend/database/select.py
Small error breaking login for new users.
=> fix: login for new user

backend/zeno_backend/processing/filtering.py, backend/zeno_backend/processing/histogram_processing.py, backend/zeno_backend/server.py, frontend/src/lib/components/instance-views/ListView.svelte, frontend/src/lib/components/instance-views/TableView.svelte, frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/components/metadata/SelectionBar.svelte, frontend/src/routes/(app)/project/[owner]/[project]/+layout.server.ts, frontend/src/routes/(app)/project/[owner]/[project]/+layout.svelte
This PR uses derived stores and makes some updates to make fewer redundant requests to the backend and speed up processing across the app.
=> fix: update when histogram and table calls are made

backend/zeno_backend/processing/histogram_processing.py, frontend/src/lib/components/instance-views/views/views/TextClassification.svelte
Was using the wrong column for calculation
=> fix: wrong col for histogram calculation

backend/zeno_backend/classes/metric.py, backend/zeno_backend/processing/metrics/map.py
LRU cache for chart calls. This is thread-safe but questionable on how useful it will be if we have a tonnnnn of traffic. I think it's worth it for now and we can revisit if it becomes a problem.
=> feat: cache of metric values for faster charts

frontend/src/routes/ping/+server.ts
Specific ping route for AWS healthcheck to not do database calls.
=> feat: ping route for frontend health check

backend/zeno_backend/classes/base.py, backend/zeno_backend/classes/chart.py, backend/zeno_backend/classes/filter.py, backend/zeno_backend/classes/folder.py, backend/zeno_backend/classes/metadata.py, backend/zeno_backend/classes/metric.py, backend/zeno_backend/classes/project.py, backend/zeno_backend/classes/report.py, backend/zeno_backend/classes/slice.py, backend/zeno_backend/classes/slice_finder.py, backend/zeno_backend/classes/table.py, backend/zeno_backend/classes/tag.py, backend/zeno_backend/classes/user.py, backend/zeno_backend/database/database.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/processing/filtering.py, backend/zeno_backend/processing/metrics/bleu.py, backend/zeno_backend/processing/slice_finder.py, backend/zeno_backend/processing/util.py, backend/zeno_backend/routers/sdk.py
As per [this linear issue](https://linear.app/zenoml/issue/ZEN-68/unify-python-docstring-capitalization), we wanted to unify python docstrings. This also completes missing ones.
=> docs: complete and unify python docstrings

backend/zeno_backend/database/insert.py
Added checks when inserting a new system to make sure both the number of data points is correct as well as that the correct columns have been added to the system.
=> fix: check for correct columns and num data points

frontend/Dockerfile.prod, frontend/src/routes/(app)/project/[owner]/[project]/layout.ts, frontend/src/routes/+layout.svelte
=> fix: remove stray layout file

backend/zeno_backend/database/insert.py, backend/zeno_backend/database/update.py, backend/zeno_backend/server.py, frontend/src/app.d.ts, frontend/src/global.d.ts, frontend/src/lib/components/report/Element.svelte, frontend/src/lib/components/report/ElementEdit.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+layout.server.ts, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
State is now set at the start by data, then updated locally with binds and set with requests.
=> feat: redo state for report, add dnd for report

backend/zeno_backend/database/delete.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, backend/zeno_backend/server.py, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/popups/ReportPopup.svelte, frontend/src/lib/stores.ts, frontend/src/lib/zenoapi/models/Chart.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Reports now also have settings where they can be made public and where user and org access can be managed.
=> feat: implement report auth management

backend/zeno_backend/server.py
=> fix: remove /ping route from logging

.github/workflows/pr.yml
=> ci: assign creator of PR as assignee

backend/zeno_backend/classes/amplitude.py
Amplitude singleton was failing w/o key present in backend.
=> fix: fix singleton amplitude tracking to work w/o key

backend/zeno_backend/routers/sdk.py, frontend/src/lib/components/instance-views/views/viewMap.ts
=> feat: check if view is valid in client

backend/zeno_backend/database/select.py, backend/zeno_backend/server.py, frontend/src/lib/api/table.ts, frontend/src/lib/components/instance-views/ComparisonView.svelte, frontend/src/lib/components/instance-views/ListView.svelte, frontend/src/lib/components/instance-views/TableView.svelte
=> fix: make comparative difference sort work again

backend/zeno_backend/database/select.py, backend/zeno_backend/processing/chart.py, frontend/src/lib/components/chart/chart-types/bar-chart/vegaSpec-bar.ts, frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts, frontend/src/lib/components/chart/chart-types/heatmap-chart/vegaSpec-heatmap.ts, frontend/src/lib/components/chart/chart-types/line-chart/vegaSpec-line.ts, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts
=> feat: order slices so that they are fetched according to their id order

backend/zeno_backend/database/select.py
Should definitely add this back but seems like the prod backend crashes on it as it runs an unsupported Postgres version.
=> fix: hotfix to remove array_position since it does not work in prod

backend/zeno_backend/database/select.py
=> feat: add back slice sorting with typecast

backend/zeno_backend/database/select.py, frontend/src/lib/components/instance-views/ComparisonView.svelte
fix comparison for non-numeric
Fix ZEN-172
Fix ZEN-181
=> fix: difference column for non-numeric

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/BeeswarmEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/HeatmapEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/RadarEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/TableEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/XCChartEncoding.svelte, frontend/src/lib/components/chart/chart-types/bar-chart/vegaSpec-bar.ts, frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts, frontend/src/lib/components/chart/chart-types/heatmap-chart/vegaSpec-heatmap.ts, frontend/src/lib/components/chart/chart-types/line-chart/vegaSpec-line.ts, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts, frontend/src/lib/components/chart/chart-types/table/Table.svelte, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/instance-views/views/views/Codegen.svelte, frontend/src/lib/components/metadata/MetadataHeader.svelte, frontend/src/lib/components/metadata/SliceHeader.svelte, frontend/src/lib/components/popups/SliceFinderPopup.svelte
=> refactor: rename model to system in ui

backend/zeno_backend/routers/sdk.py, frontend/src/lib/components/general/Markdown.svelte, frontend/src/lib/components/instance-views/views/viewMap.ts, frontend/src/lib/components/instance-views/views/views/OpenAIChatMarkdown.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat-markdown/AssistantBlock.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat-markdown/SystemBlock.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat-markdown/UserBlock.svelte, frontend/src/lib/components/report/TextElement.svelte
=> feat: add markdown instance view for openai-chat

backend/zeno_backend/routers/sdk.py, frontend/src/lib/components/instance-views/views/viewMap.ts, frontend/src/lib/components/instance-views/views/views/SpaceSeparatedValues.svelte
Adds a view for space-separated values, as was supported before:
Fix ZEN-187
=> feat: add space-separated-values

frontend/src/lib/components/general/Markdown.svelte, frontend/src/lib/components/instance-views/views/views/OpenAIChatMarkdown.svelte
small formatting issues in markdown chat.
=> fix: small rendering fixes openai-chat

backend/zeno_backend/routers/sdk.py
=> feat: add route for determining the minimum version number of the client

.github/workflows/pr.yml
Actually, this did not fix Dependabot. Hope this does. Hard to test....
=> ci: fix PR assignment CI

frontend/src/routes/(user)/signup/+page.svelte, frontend/src/routes/tos/+page.svelte
=> feat: add terms of service before signup

frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/routes/(app)/(home)/[user]/projects/+page.svelte, frontend/src/routes/(app)/(home)/[user]/reports/+page.svelte
Moves the banner to the top. Previously, it was at the very bottom of the page.
=> fix: fix project and report banner positioning

backend/zeno_backend/database/select.py, backend/zeno_backend/processing/filtering.py, backend/zeno_backend/processing/histogram_processing.py
Two main fixes:
* Always derive slice column ID from name and model to avoid issues on dataset updates
* Slight performance updates to histogram calculation
=> fix: slice reusability on db upload & SQL updates

frontend/src/lib/components/instance-views/views/views/AudioTranscription.svelte
Fix audio rendering CORS issues by using src directly.
=> fix: direct access audio for CORS

frontend/src/lib/components/instance-views/views/views/OpenAIChat.svelte, frontend/src/lib/components/instance-views/views/views/OpenAIChatMarkdown.svelte
due to key issues long chats were not rendering correctly.
=> fix: fix rendering of long markdown

backend/Dockerfile.prod
Should not reload in prod, and was preventing multiple workers.
=> fix: remove reload from prod

backend/zeno_backend/routers/sdk.py
The format for the label column was incorrect on upload
Fix ZEN-211
=> fix: label optional

backend/init.sql, backend/zeno_backend/classes/user.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, backend/zeno_backend/routers/sdk.py, backend/zeno_backend/server.py
Changes backend amplitude tracking to use cognito ID.
Fix ZEN-208
=> refactor: backend amplitude use cognito ids

frontend/src/routes/(user)/signup/+page.svelte
=> fix: show password requirements

backend/zeno_backend/routers/sdk.py, frontend/src/lib/components/instance-views/views/viewMap.ts, frontend/src/lib/components/instance-views/views/views/RAG.svelte, frontend/src/lib/components/instance-views/views/views/rag/RetrievedBlock.svelte
=> feat: add instance view for RAG

frontend/src/lib/components/chart/chart-types/bar-chart/BarChart.svelte, frontend/src/lib/components/chart/chart-types/bar-chart/vegaSpec-bar.ts, frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte, frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts, frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/report/ChartElement.svelte, frontend/src/lib/components/report/Element.svelte, frontend/src/routes/(app)/+layout.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Fix ZEN-220
This isn't the perfect fix, long term we want to think of better ways of rendering charts and instances. But it makes them usable.
=> fix: fix report rendering on mobile

frontend/src/lib/components/instance-views/views/views/OpenAIChat.svelte, frontend/src/lib/components/instance-views/views/views/OpenAIChatMarkdown.svelte, frontend/src/lib/components/instance-views/views/views/RAG.svelte
=> feat: collapse openai chat

backend/zeno_backend/classes/report.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, frontend/src/lib/components/report/ElementEdit.svelte, frontend/src/lib/zenoapi/models/ReportElement.ts
Stray chartID was breaking chart logic
=> fix: fix broken reports with stray chartID

backend/zeno_backend/database/select.py
sharing reports broke homescreen due to indexing issues
=> fix: sharing reports

frontend/src/lib/components/metadata/MetadataHeader.svelte
=> feat: sort models and metrics in the dropdown

frontend/src/lib/components/metadata/ChipsWrapper.svelte
=> feat: add addslice button to selection predicates

backend/zeno_backend/server.py
Fixed the backend key and add more events.
=> fix: update amplitude key and add more events

frontend/src/routes/(user)/signup/+page.server.ts, frontend/src/routes/(user)/signup/+page.svelte
=> fix: allow only alphanumeric usernames with dashes

frontend/src/lib/components/metadata/cells/SliceCell.svelte, frontend/src/lib/components/metadata/cells/TagCell.svelte, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/components/report/ElementEdit.svelte, frontend/src/lib/components/report/Report.svelte, frontend/src/lib/components/settings/OrganizationsTable.svelte
=> feat: add delete confirmation popup when deleting something

backend/zeno_backend/database/insert.py, backend/zeno_backend/server.py, frontend/src/lib/components/popups/SlicePopup.svelte, frontend/src/lib/zenoapi/services/ZenoService.ts
=> feat: use slice name as parent folder name when adding all slices

frontend/src/lib/components/chart/ChartHomeBlock.svelte
=> feat: confirm delete chart

backend/init.sql, backend/zeno_backend/classes/project.py, backend/zeno_backend/database/copy.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, backend/zeno_backend/processing/histogram_processing.py, backend/zeno_backend/routers/sdk.py, backend/zeno_backend/server.py, frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/NominalMetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/vegaSpecs.ts, frontend/src/lib/components/popups/CopyProjectPopup.svelte, frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/lib/zenoapi/models/Project.ts, frontend/src/lib/zenoapi/models/ProjectCopy.ts
Remove old parameters from projects.
MUST BE PAIRED WITH https://github.com/zeno-ml/zeno-client/pull/32
Fix ZEN-240
=> refactor: remove data_url and calcualte_histograms from projects

backend/zeno_backend/database/select.py, backend/zeno_backend/server.py, frontend/src/lib/components/popups/OrganizationPopup.svelte, frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/lib/components/popups/ReportPopup.svelte, frontend/src/lib/components/settings/OrganizationsTable.svelte
=> fix: fix admin editor on projects

frontend/src/routes/(app)/project/[owner]/[project]/+layout.svelte
=> fix: don't reset selections if model changes

backend/zeno_backend/classes/report.py, backend/zeno_backend/database/select.py, frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/lib/zenoapi/models/SliceElementOptions.ts
=> feat: add a button to go directly to the project's slice from a report

frontend/src/lib/components/general/Header.svelte
=> fix: correctly concatenate URL paths

frontend/src/lib/components/instance-views/views/views/OpenAIChatMarkdown.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat-markdown/AssistantBlock.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat-markdown/UserBlock.svelte, frontend/src/lib/components/instance-views/views/views/openai-chat/UserBlock.svelte
Allows for multiple blocks in output
=> feat: blocks in output for OpenAI Chat markdown

backend/zeno_backend/database/select.py, frontend/src/lib/components/report/elements/SliceElement.svelte
Fix SQL for report home page and fix alignment on slice element headers in reports.
Fix ZEN-252
=> fix: report page and slice element header

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/lib/components/popups/ReportPopup.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Fixes:
* Navigation to comparison tab
* Flickering of users/organizations menu
* Sets newly added element to edit mode in reports
=> fix: misc fixes

frontend/src/lib/components/metadata/cells/SliceCellResult.svelte
=> fix: slice update on edit

backend/zeno_backend/classes/filter.py, frontend/src/lib/components/metadata/Tags.svelte, frontend/src/lib/components/metadata/cells/SliceCell.svelte, frontend/src/lib/zenoapi/models/FilterPredicate.ts, frontend/src/lib/zenoapi/services/ZenoService.ts
Fix ZEN-257 by using strict value options to avoid value casting automatically.
Also fixes nonexistent slice being selected on slice delete.
=> fix: boolean slices

backend/zeno_backend/classes/project.py, backend/zeno_backend/database/select.py, frontend/src/lib/zenoapi/models/ProjectState.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/project/[owner]/[project]/+layout.server.ts, frontend/src/routes/(app)/project/[owner]/[project]/[page=exploreOrCompare]/+page.svelte
=> feat: show banner when no data in project.

frontend/src/lib/components/metadata/cells/MetadataCell.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte
=> fix: fix flaky selections on histograms

frontend/src/app.html
=> fix: small seo changes

backend/zeno_backend/database/select.py
=> fix: empty projects break homescreen

backend/zeno_backend/database/delete.py, backend/zeno_backend/routers/sdk.py
=> feat: delete systems using API

backend/zeno_backend/database/copy.py
=> fix: copying projects

frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte
Try to fix continuous histogram
=> fix: attempt fix drag?

frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte
Fix vega continuous filtering
Fix ZEN-267
=> fix: update continuous filtering

frontend/src/routes/(app)/(home)/+layout.svelte, frontend/src/routes/(app)/(home)/[user]/projects/+page.svelte, frontend/src/routes/(app)/(home)/[user]/reports/+page.svelte, frontend/src/routes/(app)/(home)/projects/+page.svelte, frontend/src/routes/(app)/(home)/reports/+page.svelte
https://github.com/zeno-ml/zeno-hub/pull/328#discussion_r1367687627
=> fix: prevent scrolling away the header

frontend/src/lib/components/instances/Instances.svelte
=> fix: add back filter bar

backend/zeno_backend/classes/project.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/util.py, backend/zeno_backend/routers/sdk.py, frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/instances/Instances.svelte, frontend/src/lib/components/instances/TableView.svelte, frontend/src/lib/components/metadata/SelectionBar.svelte, frontend/src/lib/components/metadata/cells/metadata-cells/BinaryMetadataCell.svelte
Supports tabular data.
Also fixes small regression with binary metadata cell.
=> feat: support tabular data with no view

backend/zeno_backend/classes/project.py, backend/zeno_backend/classes/report.py, backend/zeno_backend/database/select.py, frontend/src/lib/components/general/LikeButton.svelte, frontend/src/lib/components/metadata/MetadataHeader.svelte, frontend/src/lib/components/metadata/SliceHeader.svelte, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/components/project/ProjectHeader.svelte, frontend/src/lib/components/report/Report.svelte, frontend/src/lib/zenoapi/models/ProjectState.ts, frontend/src/lib/zenoapi/models/ReportResponse.ts, frontend/src/lib/zenoapi/models/ReportStats.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/(home)/[user]/reports/+page.svelte, frontend/src/routes/(app)/(home)/reports/+page.svelte, frontend/src/routes/(app)/+layout.svelte, frontend/src/routes/(app)/project/[owner]/[project]/+layout.server.ts, frontend/src/routes/(app)/project/[owner]/[project]/[page=exploreOrCompare]/+page.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+layout.server.ts, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
=> feat: add likes and titles to projects and reports

backend/zeno_backend/server.py, frontend/src/lib/components/instances/ComparisonView.svelte, frontend/src/lib/components/instances/ListView.svelte, frontend/src/lib/components/instances/TableView.svelte, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/components/report/Element.svelte, frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/lib/zenoapi/models/Body_upload_dataset_schema.ts, frontend/src/lib/zenoapi/models/Project.ts, frontend/src/lib/zenoapi/services/ZenoService.ts
Fix two issues:
* Check that chartOptions exist before selecting chart
* Fetch instance view from string spec for rendering.
=> fix: fetch instance view for report slices

frontend/src/lib/components/metadata/cells/FolderCell.svelte
=> fix: folder sizing

frontend/src/lib/components/general/LikeButton.svelte
=> fix: update like button to show tooltip only on heart

frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte, frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts, frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts
Not a perfect solution but at least makes them work again.
fix ZEN-249
=> fix: hotfix beeswarm and radar sizes

frontend/src/app.css, frontend/src/app.d.ts, frontend/src/routes/+layout.svelte
Fix ZEN-90
I think it's kind of sick but maybe a personal opinion if you try it out.
=> feat: view transitions

backend/zeno_backend/database/copy.py
=> fix: copy folders and add slices to them as well when copying a project

backend/zeno_backend/processing/chart.py, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/MetricsEncodingMultiChoice.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/ModelsEncodingMultiChoice.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/SlicesEncodingMultiChoice.svelte
=> feat: add checkbox to select all models/metrics/slices for a chart

frontend/.yalc/@zeno-ml/zeno-instance-views/yalc.sig, frontend/src/lib/components/general/HomeCardsContainer.svelte, frontend/src/lib/components/project/Project.svelte, frontend/src/lib/components/report/Report.svelte, frontend/src/routes/(app)/(home)/+layout.svelte, frontend/src/routes/(app)/(home)/[user]/projects/+page.svelte, frontend/src/routes/(app)/(home)/[user]/reports/+page.svelte, frontend/src/routes/(app)/(home)/projects/+page.svelte, frontend/src/routes/(app)/(home)/reports/+page.svelte, frontend/src/routes/(app)/project/[owner]/[project]/[page=exploreOrCompare]/+page.svelte, frontend/tailwind.config.js
Use a grid layout to size homescreen, and remove grouping of projects/reports
=> feat: grid layout for homescreen

frontend/src/lib/components/metadata/cells/FolderCell.svelte, frontend/src/lib/components/metadata/cells/SliceCell.svelte
=> fix: truncate slice name if long

backend/zeno_backend/classes/project.py, backend/zeno_backend/classes/report.py, frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/lib/components/popups/ReportPopup.svelte, frontend/src/lib/zenoapi/models/Project.ts, frontend/src/lib/zenoapi/models/Report.ts, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Removing optional caused a regression.
=> fix: make created and updated optional for client

frontend/src/lib/components/popups/ProjectPopup.svelte, frontend/src/lib/components/popups/ReportPopup.svelte
=> fix: remove enter listener on popups

frontend/src/lib/components/home/EntryOptions.svelte, frontend/src/lib/components/home/HomeCard.svelte, frontend/src/routes/(app)/home/[user]/+page.server.ts, frontend/src/routes/(app)/home/[user]/+page.svelte
* Could have duplicate keyed entries
* Add back delete modal
=> fix: fix remove and keyed entries

backend/zeno_backend/database/select.py
This could lead to app crashes in the worst case as we got duplicate keys if projects were fetched twice.
I hope this is a 
fix ZEN-323
Will need to test more thoroughly, though. Was not able to test locally as the keyed each broke before this change when I shared with an Org I was a member of.
=> fix: remove duplicate projects and reports

backend/zeno_backend/processing/slice_finder.py, backend/zeno_backend/processing/util.py
Fixes comparative slice finder for second option
Fix ZEN-324
=> fix: comparative slice finder

frontend/src/routes/(app)/home/+page.svelte
=> fix: keyed home entries

backend/zeno_backend/classes/base.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/util.py, backend/zeno_backend/server.py, frontend/src/lib/api/table.ts, frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/components/metadata/cells/MetadataCell.svelte, frontend/src/lib/util/util.ts, frontend/src/lib/zenoapi/models/MetadataType.ts, frontend/src/lib/zenoapi/models/ZenoColumnType.ts
Add embedding as a column type for later work on similarity search, etc.
=> feat: add embedding metadata type

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/MetricsEncodingDropdown.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/MetricsEncodingMultiChoice.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/ModelsEncodingDropdown.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/ModelsEncodingMultiChoice.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/SlicesEncodingDropdown.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/encoding-components/SlicesEncodingMultiChoice.svelte, frontend/src/lib/components/popups/FilterEntry.svelte, frontend/src/lib/components/popups/SliceFinderPopup.svelte, frontend/src/lib/components/report/elements/ChartElementEdit.svelte, frontend/src/lib/components/report/elements/SliceElementEdit.svelte, frontend/src/lib/util/util.ts, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Fix ZEN-322
A bit of a hot-fix, I don't know why special characters get rendered so oddly by svelecte.
=> fix: character rendering for svelecte

frontend/src/lib/components/instances/TableView.svelte, frontend/src/lib/components/metadata/MetadataPanel.svelte, frontend/src/routes/(app)/project/[owner]/[project]/[page=exploreOrCompare]/+page.svelte
Fixes overflow on large tables.
I couldn't figure out the right dynamic way to do it and wasted a couple of hours so just hardcoded.
=> fix: fix overflow on big table

backend/zeno_backend/instance_views/space-separated-values.json, frontend/package.json
Match updates with https://github.com/zeno-ml/zeno-instance-views/pull/32
=> fix: update views to match new TS update

frontend/src/lib/components/general/Spinner.svelte, frontend/src/lib/components/report/elements/ChartElement.svelte, frontend/src/routes/(app)/+layout.svelte
Simple zeno svg loading spinner
=> feat: simple zeno spinner

frontend/src/lib/components/general/LikeButton.svelte, frontend/src/lib/components/general/Tooltip.svelte, frontend/src/lib/components/home/EntryStat.svelte, frontend/src/lib/components/home/HomeCard.svelte, frontend/src/lib/components/metadata/MetadataHeader.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
=> feat: redo homescreen icons

backend/zeno_backend/database/insert.py, frontend/src/lib/components/report/ElementContainer.svelte, frontend/src/lib/components/report/elements/ChartElement.svelte, frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
* Fix overflow on charts
* Center spinner
* Fix issue where position was set wrong on new blocks
* Add one up/one down buttons to move without drag
=> feat: fix small report issues, add single-block move

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/general/LikeButton.svelte, frontend/src/lib/components/home/HomeSearchBar.svelte, frontend/src/lib/components/project/ProjectHeader.svelte, frontend/src/lib/components/project/ProjectSidebar.svelte, frontend/src/routes/(app)/+layout.svelte, frontend/src/routes/(app)/account/+page.svelte, frontend/src/routes/(app)/home/+layout.svelte, frontend/src/routes/(app)/home/[user]/+page.svelte, frontend/src/routes/(app)/project/[owner]/[project]/+layout.svelte, frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte
Updated headers. Lots of changes on all pages so worth running locally.
=> feat: updated header styles

frontend/src/routes/(app)/project/[owner]/[project]/[page=exploreOrCompare]/+page.svelte
I think this is a 
fix ZEN-327
can you test this as well @cabreraalex ? All the cases I tried worked.
=> fix: responsive max table width

frontend/src/lib/instance-views/elements/Image.svelte, frontend/src/lib/instance-views/elements/List.svelte, frontend/src/lib/instance-views/elements/Message.svelte, frontend/src/lib/instance-views/elements/SeparatedValues.svelte, frontend/src/lib/instance-views/elements/Text.svelte, frontend/src/lib/instance-views/elements/VStack.svelte, frontend/src/lib/instance-views/schema.json, frontend/src/lib/instance-views/schema.ts
=> style: remove the view part from all views in the schema

frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
Fixes every element re-rendering in reports on edit.
=> fix: crazy report behavior with requests

frontend/src/lib/components/report/ElementContainer.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
=> feat: double click and escape report edit

backend/zeno_backend/database/select.py, frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/util/util.ts
Adds ORDER BY to make it deterministic.
Fix ZEN-348
=> feat: add order to instances, histograms, and charts

backend/zeno_backend/routers/account.py, backend/zeno_backend/routers/chart.py, backend/zeno_backend/routers/folder.py, backend/zeno_backend/routers/metadata.py, backend/zeno_backend/routers/metric.py, backend/zeno_backend/routers/project.py, backend/zeno_backend/routers/report.py, backend/zeno_backend/routers/slice.py, backend/zeno_backend/routers/table.py, backend/zeno_backend/routers/tag.py, backend/zeno_backend/util.py
Recommended way to do it: https://fastapi.tiangolo.com/tutorial/handling-errors/
=> fix: replace returns with throws

frontend/src/app.html, frontend/src/routes/(app)/account/+page.svelte, frontend/src/routes/(app)/home/+page.svelte, frontend/src/routes/(app)/home/[user]/+page.svelte, frontend/src/routes/(app)/project/[uuid]/[name]/+layout.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
For SEO and our own sanity
Fix ZEN-347
=> feat: add titles and descriptions to pages

backend/zeno_backend/database/update.py
=> fix: don't delete old metric if a new one is added

backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/routers/chart.py, backend/zeno_backend/routers/metadata.py, backend/zeno_backend/routers/project.py, backend/zeno_backend/routers/report.py, backend/zeno_backend/routers/sdk.py, backend/zeno_backend/routers/slice.py, backend/zeno_backend/routers/table.py, backend/zeno_backend/util.py, frontend/src/lib/zenoapi/services/ZenoService.ts
=> refactor: raise errors where they occur instead of returning None

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/general/UserButton.svelte, frontend/src/lib/components/project/ProjectHeader.svelte
Unify the headers a little so that some changes don't have to be made in both files.
=> refactor: unify headers

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/general/Help.svelte, frontend/src/routes/(app)/account/+page.svelte, frontend/src/routes/(app)/home/+layout.svelte, frontend/src/routes/(app)/project/[uuid]/[name]/+layout.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte, frontend/src/routes/playground/+page.svelte
fix ZEN-343
https://github.com/zeno-ml/zeno-hub/assets/5690524/41823a49-29bd-4bea-b14b-58cbdc24bbcf
=> feat: add a help button throughout many parts of hub

backend/init.sql, backend/zeno_backend/classes/project.py
I think 10 is bad in almost every case.
=> feat: bump default samples per page

frontend/src/routes/embed/entry/featured/[numItems=integer]/+page.svelte
Was causing some link failures on homepage.
=> fix: route for embed iframe

frontend/src/routes/(user)/forgot/[username]/+page.svelte, frontend/src/routes/(user)/login/+page.svelte, frontend/src/routes/(user)/signup/+page.svelte, frontend/src/routes/(user)/verify/[username]/+page.svelte, frontend/tailwind.config.js
=> fix: move signup error up, make red

frontend/package-lock.json, frontend/package.json, frontend/src/global.d.ts
Fix ZEN-355
Depends on ZEN-353 and ZEN-351
=> build: remove svelte-dnd

frontend/package.json, frontend/src/lib/instance-views/schema.json, frontend/src/lib/instance-views/schema.ts
Also snake_case npm command to match other commands.
=> fix: unrequire label and output in schema

frontend/src/lib/components/instances/ListView.svelte
=> fix: display instance number localized

frontend/src/lib/components/chart/chart-types/bar-chart/BarChart.svelte, frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte, frontend/src/lib/components/chart/chart-types/heatmap-chart/HeatMap.svelte, frontend/src/lib/components/chart/chart-types/line-chart/LineChart.svelte, frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte
=> feat: name downloaded file according to chart name

frontend/src/routes/playground/+page.svelte
=> fix: make playground views overflow y

frontend/src/lib/components/metadata/SelectionBar.svelte, frontend/src/lib/components/popups/UpdateTagPopup.svelte
=> feat: ad option to add selected instances to a tag

backend/zeno_backend/database/select.py, backend/zeno_backend/routers/slice.py, frontend/src/lib/components/metadata/cells/SliceCell.svelte, frontend/src/lib/components/metadata/cells/TagCell.svelte, frontend/src/lib/zenoapi/models/HistogramBucket.ts, frontend/src/lib/zenoapi/services/ZenoService.ts
=> feat: add buttons to copy all ids of a slice's/tag's instances

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md
Makes it clear what information would be useful for us.
=> docs: add issue templates

backend/zeno_backend/database/select.py
This could break the frontend as we had duplicate keys when the order was not deterministic.
=> fix: ensure consistnet order to prevent duplicate keys

frontend/src/lib/components/popups/NewOrganizationPopup.svelte, frontend/src/lib/components/settings/OrganizationsTable.svelte, frontend/src/routes/(app)/account/+page.server.ts, frontend/src/routes/(app)/account/+page.svelte
Was calling wrong function, also add popup for naming.
Fix ZEN-375
=> fix: fix organizations table in account

.github/workflows/ci.yml, backend/init.sql, backend/zeno_backend/database/select.py, frontend/tests/project.test.ts
fix ZEN-369
Needs a minor DB update.
=> fix: sort instance ids in natural order

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/BeeswarmEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/RadarEncoding.svelte, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/TableEncoding.svelte, frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte, frontend/src/lib/components/chart/chart-types/table/Table.svelte, frontend/src/lib/instance-views/elements/List.svelte
update styles for new prettier version
=> fix: prettier build

frontend/src/lib/components/instances/ComparisonView.svelte, frontend/src/lib/components/instances/ListView.svelte, frontend/src/lib/components/instances/TableView.svelte, frontend/src/lib/components/metadata/SelectionBar.svelte, frontend/src/lib/instance-views/InstanceView.svelte
=> fix: only logged-in users can select items or create tags

frontend/src/routes/(app)/home/+page.server.ts
=> fix: load only 20 items in explore and then infinite scroll

frontend/src/routes/(user)/login/+page.svelte
=> feat: always show reset password link

frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/lib/components/report/elements/TagElement.svelte
=> fix: correctly deep link into projects from report tags and slices

backend/zeno_backend/routers/chart.py, backend/zeno_backend/routers/folder.py, backend/zeno_backend/routers/project.py, backend/zeno_backend/routers/report.py, backend/zeno_backend/routers/slice.py, backend/zeno_backend/routers/tag.py, backend/zeno_backend/util.py
Previously, we only checked for valid access on load. However, we never checked on update whether someone actually had edit rights.
=> fix: check whether a user is a editor before making a change

README.md
Small blurb to describe self-hosting.
Fix ZEN-385
=> docs: self-host

backend/zeno_backend/database/copy.py, frontend/src/lib/components/home/HomeCard.svelte
=> fix: fix copy bug and only show menu when logged in

backend/zeno_backend/database/select.py, backend/zeno_backend/database/util.py, backend/zeno_backend/routers/sdk.py
=> fix: detect nonexistent standard views

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/TableEncoding.svelte, frontend/src/lib/components/chart/chart-types/table/Table.svelte, frontend/src/lib/components/chart/chart-types/table/TableRow.svelte, frontend/src/routes/(app)/project/[uuid]/[name]/chart/[chartIndex=integer]/+page.svelte
Clean's up issues with the table visualization
=> fix: clean up table view, fix bugs

frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts, frontend/src/lib/components/report/elements/ChartElement.svelte
=> fix: sizing of radar

frontend/src/lib/components/home/HomeSearchBar.svelte, frontend/src/routes/(app)/home/+page.svelte, frontend/src/routes/(app)/home/[user]/+page.svelte, frontend/src/routes/(user)/login/+page.svelte
=> feat: standardize spinner for login and home

frontend/src/lib/components/instances/ComparisonView.svelte, frontend/src/lib/components/instances/ListView.svelte, frontend/src/lib/components/instances/TableView.svelte, frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/lib/components/report/elements/TagElement.svelte, frontend/src/lib/instance-views/InstanceView.svelte, frontend/src/routes/playground/+page.svelte
=> fix: remove stores from instances

frontend/src/lib/instance-views/elements/VStack.svelte
=> fix: show vstack keys in order specified

frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte
=> fix: small regression in beeswarm

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/project/ProjectHeader.svelte
=> feat: copy links in projects and reports

frontend/src/lib/components/project/ProjectHeader.svelte
=> fix: project header height

.github/workflows/ci.yml
=> build: update python ci

frontend/src/lib/components/report/Element.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
=> fix: projects wrap and stray padding

backend/zeno_backend/classes/user.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, backend/zeno_backend/routers/account.py, db/init.sql, db/test-data.sql, frontend/src/lib/components/settings/Account.svelte, frontend/src/lib/zenoapi/models/User.ts, frontend/src/routes/(app)/account/+page.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
Fix ZEN-255
Display name for reports and projects. Currently only shown on reports, not on home or in projects - I think just username for those to make sure people aren't impersonating on the home screen?
Defaults to username.
Commands to alter table:
```
ALTER TABLE users ADD COLUMN display_name text;
UPDATE users SET display_name = users.name;
ALTER TABLE users ALTER COLUMN display_name SET NOT NULL;
```
=> feat: add display name to users

backend/zeno_backend/classes/user.py, backend/zeno_backend/database/delete.py, backend/zeno_backend/database/insert.py, backend/zeno_backend/database/select.py, backend/zeno_backend/database/update.py, backend/zeno_backend/routers/report.py, db/init.sql, frontend/src/lib/zenoapi/index.ts, frontend/src/lib/zenoapi/models/Author.ts, frontend/src/lib/zenoapi/services/ZenoService.ts, frontend/src/routes/(app)/report/[id]/[name]/+layout.server.ts, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
fix ZEN-256
Commands to alter db:
```sql
CREATE TABLE report_author (
id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
report_id integer NOT NULL REFERENCES reports(id) ON DELETE CASCADE ON UPDATE CASCADE,
position integer NOT NULL
);
INSERT INTO report_author (user_id, report_id, position) (SELECT u.id, r.id, 0 from users as u JOIN reports as r ON r.owner_id = u.id);
```
=> feat: allow multiple authors of a report

backend/zeno_backend/processing/histogram_processing.py
=> fix: add values that lie directly at bucket_end to last bucket

frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
Buttons weren't rendering correctly
=> fix: buttons in report banner

frontend/src/routes/(user)/login/+page.svelte
=> fix: correctly redirect after login

backend/zeno_backend/processing/chart.py, frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/HeatmapEncoding.svelte
Fixes metric calculation for slice/model heatmap.
=> fix: heatmap encoding

frontend/src/lib/components/chart/chart-types/table/Table.svelte
=> feat: csv download table

frontend/src/lib/components/chart/chart-types/table/Table.svelte
Correctly label slices in table export
=> fix: table export

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/BeeswarmEncoding.svelte, frontend/src/lib/components/chart/chart-types/bar-chart/BarChart.svelte, frontend/src/lib/components/chart/chart-types/bar-chart/vegaSpec-bar.ts, frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte, frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts, frontend/src/lib/components/chart/chart-types/heatmap-chart/HeatMap.svelte, frontend/src/lib/components/chart/chart-types/heatmap-chart/vegaSpec-heatmap.ts, frontend/src/lib/components/chart/chart-types/line-chart/LineChart.svelte, frontend/src/lib/components/chart/chart-types/line-chart/vegaSpec-line.ts, frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte, frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts, frontend/src/lib/components/chart/config.ts
Increases the font size for charts overall. Not sure entirely what the right font size is but it's pretty easy to change again and will likely unblock people.
=> feat: increase chart font size overall

backend/zeno_backend/database/delete.py
Noticed our cascade foreign keys should take care of this.
fix ZEN-427
=> fix: remove extra delete

frontend/src/lib/components/report/Banner.svelte, frontend/src/lib/components/report/LinkedProjects.svelte, frontend/src/lib/components/report/elements/ChartElement.svelte, frontend/src/lib/components/report/elements/SliceElement.svelte, frontend/src/lib/components/report/elements/TagElement.svelte, frontend/src/routes/(app)/report/[id]/[name]/+page.svelte
=> fix: gracefully fail reports if elements or projects don't exist naymore

frontend/src/lib/components/general/Spinner.svelte
Triangles were partly overlapping or had too much spacing and were not all colored correctly.
=> fix: correct spinner triangles

frontend/src/lib/components/chart/chart-page/chart-header/EditHeader.svelte, frontend/src/lib/components/chart/chart-page/chart-header/SettingsButton.svelte, frontend/src/lib/components/chart/chart-page/chart-header/ViewHeader.svelte, frontend/src/lib/components/general/CircleIconButton.svelte, frontend/src/lib/components/general/Header.svelte, frontend/src/routes/(app)/project/[uuid]/[name]/chart/[chartIndex=integer]/+page.svelte
=> fix: fix positioning and look of chart settings button

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/components/general/HelpButton.svelte
=> style: unify header buttons

backend/zeno_backend/routers/sdk.py, backend/zeno_backend/util.py
Enables project editors to update project data and systems.
fix ZEN-403
Requires https://github.com/zeno-ml/zeno-client/pull/50
=> feat: allow project editor to update data

frontend/src/lib/components/general/Header.svelte, frontend/src/lib/util/tooltip.ts, frontend/src/routes/(app)/home/+layout.svelte
Switching between explore and home wasn't working well. ALso added spinner to header whenever navigating to show if it's being slow after you clicked (necessary after removing view transitions)
=> fix: tooltip updates and loading spinner on navigate

frontend/src/lib/components/metadata/Histograms.svelte, frontend/src/lib/components/metadata/cells/MetadataCell.svelte
We were inadvertently hiding most nominal histograms
=> fix: regression, show nominal hists

frontend/src/lib/components/instances/Instances.svelte
=> fix: show comparison view even without metric

frontend/src/lib/components/chart/chart-page/encoding/chart-encoding/BeeswarmEncoding.svelte
=> fix: fix bug with system or slice change for fixed beeswarm dimension
