zeno-ml/zeno-hub

frontend/.env.example
frontend/src/routes/(app)/+layout.server.ts
frontend/src/routes/(user)/login/+page.server.ts

This PR (temporarily) adds the option to run on insecure http servers.
This should be fixed in a future PR (noted https://linear.app/zenoml/issue/ZEN-38/infra-add-encryption).

Add the option to do insecure http

---

frontend/src/lib/components/metadata/cells/metadata-cells/BinaryMetadataCell.svelte
frontend/src/lib/stores.ts

If no metric is selected, the binary metadata background color was black. This has been changed to our primary color to make it match all other histogams.

feat: change binary metadata color if no metric

---

backend/zeno_backend/server.py
frontend/src/lib/zenoapi/services/ZenoService.ts
frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.server.ts
frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.server.ts

Since the project parameter changed with our change of referencing projects as owner/project, charts now need to first fetch the project uuid before being fetched.

fix: correct chart fetching with project uuid

---

frontend/src/lib/components/instance-views/ComparisonView.svelte

This somehow led to a duplicate keys exception. We might want to bring this back after further investigation.

fix: remove key in compare table

---

frontend/src/lib/components/general/Header.svelte

Only shows collapse on tabs where it makes sense.

fix: only show collapse on explore & compare

---

frontend/src/lib/components/general/Header.svelte
frontend/src/routes/(user)/logout/+page.server.ts

Show a login button when logged out on home screen. Only show account management button when logged in.
Fixes: https://linear.app/zenoml/issue/ZEN-84/fix-login-flow-and-options
Logged in:
Logged out:

feat: login/logout header functionality

---

backend/zeno_backend/database/insert.py
backend/zeno_backend/database/select.py
backend/zeno_backend/database/update.py
backend/zeno_backend/server.py
frontend/src/lib/components/chart/ChartHomeBlock.svelte
frontend/src/lib/components/instance-views/ComparisonView.svelte
frontend/src/lib/components/instance-views/InstanceView.svelte
frontend/src/lib/components/instance-views/views/views/AudioTranscription.svelte
frontend/src/lib/components/metadata/MetadataHeader.svelte
frontend/src/lib/components/metadata/Slices.svelte
frontend/src/lib/components/metadata/Tags.svelte
frontend/src/lib/components/metadata/cells/FolderCell.svelte
frontend/src/lib/components/metadata/cells/SliceCell.svelte
frontend/src/lib/components/metadata/cells/SliceFinderCell.svelte
frontend/src/lib/components/metadata/cells/TagCell.svelte
frontend/src/lib/components/metadata/chips/TagChip.svelte
frontend/src/lib/components/popups/FolderPopup.svelte
frontend/src/lib/components/popups/SlicePopup.svelte
frontend/src/lib/components/popups/TagPopup.svelte
frontend/src/routes/(app)/project/[owner]/[project]/+layout.server.ts
frontend/src/routes/(app)/project/[owner]/[project]/+layout.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte

Sveltekit was caching get requests for things like slices, causing it to not re-pull changes when tabs were changed. This is primarily fixed by calling `invalidateAll()`. This PR fixes that along with some other fixes/changes:
* Don't call get after post, just return ID and add locally for "post" calls
* Run initial fetch in parallel for performance
* Fix what is used to render data to separate from data_id for tags
Fixes:
[ZEN-92 : slices are not always updated on the frontend without refresh](https://linear.app/zenoml/issue/ZEN-92/slices-are-not-always-updated-on-the-frontend-without-refresh)
[ZEN-96 : metric dropdown is blank when navigating home and back to a project](https://linear.app/zenoml/issue/ZEN-96/metric-dropdown-is-blank-when-navigating-home-and-back-to-a-project)

fix: inconsistent server updates, don't run get after post, fix tags, 

---

backend/zeno_backend/database/util.py
frontend/src/lib/api/metadata.ts
frontend/src/lib/components/metadata/cells/MetadataCell.svelte

Shift chart selection to frontend, don't filter out histograms.
Original suggestion by @Sparkier , think its better, easier to update frontend visualizations in the future.

fix: do metadata chart selection in frontend

---

backend/zeno_backend/classes/chart.py
backend/zeno_backend/processing/chart.py
backend/zeno_backend/processing/histogram_processing.py
backend/zeno_backend/processing/metrics/map.py
backend/zeno_backend/server.py
frontend/src/lib/components/chart/chart-types/radar-chart/RadarChart.svelte
frontend/src/routes/(app)/+layout.server.ts

Move LRU cache to cache table data, which is simpler than caching metric calls.

feat: move cache to chart data

---

frontend/src/lib/components/chart/chart-page/view-selection/ViewSelection.svelte
frontend/src/lib/components/chart/chart-types/beeswarm-chart/BeeswarmChart.svelte
frontend/src/lib/util/charts.ts

Sets slices so that something gets displayed when switching chart types.
Also fixes the Beeswarm chart since it was buggy with the count metric before.

fix: set correct slices when switching between chart types

---

frontend/src/lib/components/chart/ChartHomeBlock.svelte
frontend/src/lib/components/chart/chart-page/chart-header/ViewHeader.svelte
frontend/src/lib/components/chart/chart-page/view-selection/ViewSelection.svelte
frontend/src/lib/components/general/Header.svelte
frontend/src/lib/components/instance-views/ComparisonView.svelte
frontend/src/lib/components/instance-views/InstanceView.svelte
frontend/src/lib/components/instance-views/ListView.svelte
frontend/src/lib/components/instance-views/TableView.svelte
frontend/src/lib/components/metadata/Histograms.svelte
frontend/src/lib/components/metadata/SelectionBar.svelte
frontend/src/lib/components/metadata/SliceHeader.svelte
frontend/src/lib/components/metadata/Tags.svelte
frontend/src/lib/components/metadata/cells/FolderCell.svelte
frontend/src/lib/components/metadata/cells/SliceCell.svelte
frontend/src/lib/components/metadata/cells/SliceFinderCell.svelte
frontend/src/lib/components/metadata/cells/metadata-cells/ContinuousMetadataCell.svelte
frontend/src/lib/components/metadata/cells/metadata-cells/NominalMetadataCell.svelte
frontend/src/lib/components/metadata/cells/metadata-cells/TextMetadataCell.svelte
frontend/src/lib/components/popups/FolderPopup.svelte
frontend/src/lib/components/popups/ProjectPopup.svelte
frontend/src/lib/components/popups/SliceFinderPopup.svelte
frontend/src/lib/components/popups/SlicePopup.svelte
frontend/src/lib/components/popups/TagPopup.svelte
frontend/src/lib/stores.ts
frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte

Must always have a project object when looking at a project (set by layout), so don't have to check everywhere.

refactor: remove project undefined checks

---

frontend/src/routes/(user)/login/+page.server.ts

Fixes the issue that the user was not in the DB directly after signup when fetching user's projects and reports.

fix: call /login on login so that user is created if not existing

---

backend/Dockerfile.prod

This PR lengthens the timeout for the prod backend from the default 5 seconds to 75 seconds. 75 seconds is chosen because it is longer than 60 seconds, which is a default that we're using in the application load balancer. See below for the recommendation for AWS.
In addition, it increases the number of workers for uvicorn to 4, because the "ping" requests will fail while doing longer requests on another thread if we only have 1 worker. This causes the worker to be killed by the load balancer, because the load balancer thinks the process is unhealthy.
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html
- Part of https://linear.app/zenoml/issue/ZEN-148/bug-502-error-and-ensuing-json-decoding-error-when-uploading-large
- NA

fix: Lengthen the timeout for the prod backend

---

frontend/src/lib/components/chart/chart-page/encoding/Encoding.svelte
frontend/src/lib/components/chart/chart-types/line-chart/LineChart.svelte

The line chart did not handle the case with the slice size metric correctly. This has now been fixed.

fix: fix line chart without metric selected

---

backend/zeno_backend/database/insert.py

When the data column did contain non-string data (e.g. arrays), the SQL alchemy insert was failing. Since the data column can be narrowed by the instance view in all cases, we can just store strings and extract information in the instance view.
fix ZEN-153
fix ZEN-147

fix: cast data column to string always

---

frontend/src/lib/components/settings/Account.svelte

This removes the feature flags setting from prod. It's not exactly what we discussed but I think this solves our problem while keeping things configurable.
Now prod users don't see this setting while on dev you can still turn on and off features individually.
fix ZEN-163

feat: hide feature flags setting in prod

---

frontend/src/lib/components/instance-views/ComparisonView.svelte

Fix a regression in difference comparison view.

fix: fix difference sorting in compare page

---

frontend/src/lib/components/chart/chart-page/view-selection/ChartElement.svelte
frontend/src/lib/components/chart/chart-page/view-selection/ViewSelection.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte

I tried a bunch of stuff to make encodings change on chart type change, but this is a bit problematic. Hence, I had to implement a hack to force the encoding component to re-render. The problem is the following:
Svelecte can only be used with dndzone when using bind:value, not with on:change, as on:change does not get triggered on reordering on elements with dndzone. However, we can't bind:value always because otherwise we have an infinite loop (value change leads to a dispatch so we can change the chart which leads to a value change).

fix: make encodings reload on chart type change

---

backend/zeno_backend/database/select.py
frontend/src/lib/api/table.ts
frontend/src/lib/components/instance-views/ComparisonView.svelte
frontend/src/lib/components/metadata/MetadataHeader.svelte

Makes the feature columns in the same column as instances.
Also fixes ZEN-184

feat: consolidate columns in comparison and fix

---

frontend/DEVELOPMENT.md
frontend/OpenAPI_back.txt
frontend/package-lock.json
frontend/package.json

Don't know if we want to do this but always changing this file is something people will forget and that's cumbersome.
The question is what happens if the file structure ever changes. I don't know how common this would be.

build: auto-override the OpenAPI file to include the BASE

---

frontend/src/lib/components/general/Banner.svelte
frontend/src/lib/components/general/Header.svelte
frontend/src/lib/components/general/HomeHeader.svelte
frontend/src/lib/components/popups/NewReportPopup.svelte
frontend/src/lib/stores.ts
frontend/src/routes/(app)/(home)/+layout.svelte
frontend/src/routes/(app)/(home)/[user]/projects/+page.svelte
frontend/src/routes/(app)/(home)/[user]/reports/+page.svelte
frontend/src/routes/(app)/(home)/projects/+page.svelte
frontend/src/routes/(app)/(home)/reports/+page.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/+page.svelte

feat: implement flat design for charts and home

---

.github/workflows/pr.yml

Does not self-assign PRs if they come from dependabot.

ci: don't assign dependabot PRs

---

frontend/src/lib/components/general/Markdown.svelte

words in reports were breaking at end of line

fix: word breaks in reports

---

frontend/src/lib/components/popups/ProjectPopup.svelte
frontend/src/lib/components/popups/ReportPopup.svelte

If we don't allow this, there is no way for people to see these projects on their home-pages.

fix: reenable sharing even if project is public already

---

frontend/src/lib/components/metadata/MetadataPanel.svelte
frontend/src/lib/components/metadata/SliceHeader.svelte

fix: move slice header up if there is no model in a project

---

backend/zeno_backend/processing/histogram_processing.py

Histograms were broken for boolean metric columns. This has now been fixed.

fix: make histograms work with metric columns that are boolean

---

backend/zeno_backend/database/delete.py
backend/zeno_backend/database/insert.py
backend/zeno_backend/server.py
frontend/src/lib/components/metadata/cells/FolderCell.svelte
frontend/src/lib/components/popups/Confirm.svelte
frontend/src/lib/components/popups/SlicePopup.svelte
frontend/src/lib/zenoapi/models/Body_upload_dataset_schema.ts
frontend/src/lib/zenoapi/models/User.ts
frontend/src/lib/zenoapi/services/ZenoService.ts

The slice popup changes if a user selects only a nominal column without entering anything else as follows:
After creation, slices will look as follows:
fix ZEN-214

feat: add option to add slices for all values of a nominal column

---

backend/zeno_backend/classes/report.py
backend/zeno_backend/classes/table.py
frontend/src/lib/components/report/ElementContainer.svelte
frontend/src/lib/components/report/ElementEdit.svelte
frontend/src/lib/components/report/elements/SliceElement.svelte
frontend/src/lib/components/report/elements/TextElement.svelte
frontend/src/lib/zenoapi/models/SliceElementSpec.ts
frontend/src/lib/zenoapi/models/SliceTableRequest.ts

https://github.com/zeno-ml/zeno-hub/assets/5690524/8593e1dc-57c3-4328-a3e2-a7b46dfad4a8

feat: show a preview of the edited element in reports

---

frontend/src/lib/components/chart/chart-types/bar-chart/vegaSpec-bar.ts
frontend/src/lib/components/chart/chart-types/beeswarm-chart/vegaSpec-beeswarm.ts
frontend/src/lib/components/chart/chart-types/line-chart/vegaSpec-line.ts
frontend/src/lib/components/chart/chart-types/radar-chart/vegaSpec-radar.ts
frontend/src/lib/components/report/Element.svelte
frontend/src/lib/components/report/elements/ChartElement.svelte
frontend/src/routes/(app)/project/[owner]/[project]/chart/[chartIndex=integer]/+page.svelte

Using the [autosize function](https://vega.github.io/vega-lite/docs/size.html#autosize) of Vega.
fix ZEN-239

fix: make sure charts always fit into report width

---

frontend/src/lib/components/report/AddElementButton.svelte
frontend/src/lib/components/report/ElementContainer.svelte
frontend/src/routes/(app)/report/[owner]/[report]/+page.svelte

Fixes reports without projects showing. Also updates styles as discussed:

feat: fix report element edit w/o project

---

backend/init.sql
backend/zeno_backend/database/update.py

Fix ZEN-266
Run following to update DB:
```SQL
ALTER TABLE projects ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE projects ADD COLUMN updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE charts ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE charts ADD COLUMN updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reports ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reports ADD COLUMN updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE report_like ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE project_like ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

feat: add created and updated columns to DB

---

backend/zeno_backend/processing/histogram_processing.py
frontend/src/lib/components/instances/TableView.svelte

* Apparently been calculating buckets for FD wrong the whole time - it returns the width of bins, not the count
* Always show ID column in table, and if in tabular view also show the label and output (which are shown in the instance view for normal data)

fix: histogram calc and table view

---

frontend/.gitignore
frontend/package.json
frontend/src/lib/components/instances/ComparisonView.svelte
frontend/src/lib/components/instances/ListView.svelte
frontend/src/lib/components/metadata/MetricRange.svelte
frontend/src/lib/components/popups/Popup.svelte
frontend/src/lib/components/report/elements/SliceElement.svelte
frontend/vite.config.ts

* Add two options to use yalc for locally using instances package: https://stackoverflow.com/questions/68670700/npm-link-dev-packages-when-using-docker-dev-containers
* Fix ZEN-295
* Fix ZEN-291 - Use grid view in instances and fixed half-width in reports for instance view to fill space. Eventually want to make it more customizable, for now it's max width of 400.
* Fix ZEN-294 - validate range and set on enter.
* Fix ZEN-289

fix: various fixes

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/general/HeaderIcon.svelte
frontend/src/lib/components/general/HomeHeader.svelte
frontend/src/lib/components/general/LikeButton.svelte
frontend/src/lib/components/general/Tooltip.svelte
frontend/src/lib/components/metadata/HistogramsHeader.svelte
frontend/src/lib/components/metadata/SliceHeader.svelte
frontend/src/lib/components/metadata/Tags.svelte
frontend/src/lib/components/metadata/cells/metadata-cells/SearchOption.svelte
frontend/src/lib/components/popups/SliceFinderPopup.svelte
frontend/src/lib/components/project/Project.svelte
frontend/src/lib/components/project/ProjectHeader.svelte
frontend/src/lib/components/project/ProjectStat.svelte
frontend/src/lib/components/report/Report.svelte
frontend/src/lib/components/settings/OrganizationsTable.svelte
frontend/src/lib/stores.ts
frontend/src/lib/util/tooltip.ts
frontend/src/routes/(app)/(home)/+layout.svelte
frontend/src/routes/+layout.svelte
frontend/src/theme/_smui-theme.scss
frontend/static/smui.css

fix ZEN-305
Implements a custom tooltip that uses the `use:` directive to listen to mouse events and uses a global tooltip state and element.

refactor: implement custom tooltip to fix errors with tooltip library

---

frontend/src/lib/components/home/HomeCard.svelte

fix: truncate project or report title to prevent overflow

---

frontend/package-lock.json
frontend/package.json

This did not work as expected without the package. To reproduce:

build: add back prettier-plugin-svelte to fix format

---

backend/zeno_backend/processing/histogram_processing.py

We were still calculating histograms wrong.
I decided to just stick with sturges, which doesn't work great for outliers and non-normal data because it picks too small of buckets.
FD was generating too many buckets, which becomes slow and expensive especially for cross-filtering.
I think sturges is good enough for now.

fix: simplify histogram calculation

---

frontend/src/lib/components/instances/ComparisonView.svelte
frontend/src/lib/components/instances/ListView.svelte
frontend/src/lib/components/instances/TableView.svelte

Using await would clear the table and reset everything, making it flash and be annoying. I think it's better doing lazy updating like this.

fix: lazy updating of lists to prevent flickering and moving screen

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/instances/ComparisonView.svelte
frontend/src/lib/components/instances/ListView.svelte
frontend/src/lib/components/instances/TableView.svelte
frontend/src/lib/components/report/elements/SliceElement.svelte
frontend/src/lib/instance-views/Error.svelte
frontend/src/lib/instance-views/InstanceView.svelte
frontend/src/lib/instance-views/elements/Audio.svelte
frontend/src/lib/instance-views/elements/Code.svelte
frontend/src/lib/instance-views/elements/Image.svelte
frontend/src/lib/instance-views/elements/List.svelte
frontend/src/lib/instance-views/elements/Markdown.svelte
frontend/src/lib/instance-views/elements/Message.svelte
frontend/src/lib/instance-views/elements/SeparatedValues.svelte
frontend/src/lib/instance-views/elements/Text.svelte
frontend/src/lib/instance-views/elements/VStack.svelte
frontend/src/lib/instance-views/resolve.ts
frontend/src/lib/instance-views/schema.json
frontend/src/lib/instance-views/schema.ts
frontend/src/routes/playground/+layout.ts
frontend/src/routes/playground/+page.svelte
frontend/src/routes/playground/samples.ts
frontend/src/routes/playground/util.ts
frontend/tailwind.config.js
package-lock.json

Instead of having a separate instance-views repo, moves it into zeno-hub and creates a playground endpoint.

refactor: move instance-views into hub

---

backend/zeno_backend/server.py
frontend/src/lib/components/report/elements/SliceElement.svelte

This is more of a hot fix to prevent the crash. We should talk about how to handle this more generally and go over all the endpoints to make sure we're handling auth correctly.
fix ZEN-346

fix: hotfix frontend crash on public report private project

---

frontend/src/lib/instance-views/elements/ThreeD.svelte
frontend/src/lib/instance-views/resolve.ts
frontend/src/lib/instance-views/schema.json
frontend/src/lib/instance-views/schema.ts
frontend/src/routes/playground/samples.ts

Adds an instance view for 3D models.
https://github.com/zeno-ml/zeno-hub/assets/5690524/d013d525-bd62-4d37-beb1-df9a818e854d
Docs update: https://github.com/zeno-ml/zenoml.com/pull/42

feat: add instance view for 3D models

---

frontend/src/lib/components/report/ElementContainer.svelte
frontend/src/lib/components/report/ElementEdit.svelte
frontend/src/routes/(app)/report/[id]/[name]/+page.svelte

Drag to move elements was buggy and slow, not even useful since we didn't auto scroll. Removed it and fixed binding to keep frontend and backend synced.
Fix ZEN-351

fix: flaky report edits, remove dnd

---

backend/zeno_backend/classes/metadata.py

The histogram would crash if there was a none value as bucket (which could happen if you provide either string or none as data in a col).

fix: prevent crash for none values as buckets

---

frontend/src/lib/components/home/EntryOptions.svelte
frontend/src/lib/components/home/HomeCard.svelte

fix: prevent overlap of container when showing options

---

frontend/src/routes/(app)/project/[uuid]/[name]/+layout.svelte

Previously, we did not correctly load selected tags.

fix: set tagIds correctly when loading a project with a tag selected

---

frontend/src/lib/components/instances/ComparisonView.svelte
frontend/src/lib/components/instances/ListView.svelte
frontend/src/lib/components/instances/TableView.svelte

Instances sometimes did not update when changing the model. This has been fixed by adding an identifier for the model column to the list. Additionally, we don't need to reload the data when changing the model. The table stays the same.

fix: make instances always reflect current model

---

backend/zeno_backend/database/select.py

When calling a project by owner/name we threw the wrong error and hence did not redirect correctly.

fix: throw correct error so frontend redirects

---

frontend/src/lib/components/home/HomeSearchBar.svelte
frontend/src/lib/components/instances/ComparisonView.svelte
frontend/src/lib/components/instances/ListView.svelte
frontend/src/lib/components/instances/TableView.svelte
frontend/src/lib/components/metadata/MetadataHeader.svelte
frontend/src/lib/components/popups/UpdateTagPopup.svelte
frontend/src/lib/components/ui/Select.svelte

We have been using the browser select element before.
Safari:
Chrome:
This adds a unified select component with a cross-browser UI:

feat: create common style for select eleemnts

---

frontend/src/lib/components/instances/TableView.svelte

Previously, it could happen that the bar at the Bottom of the table was floating mid screen. This has been fixed.

fix: make table full height even if few small elemnts

---

backend/zeno_backend/database/update.py

Currently the owner can't be eupdated anyway, and the way we fetched the owner from the report field did not work when the owner had a display name set.

fix: don't update owner when updating report

---

backend/zeno_backend/database/select.py

Think we should order models, slices, and metrics per default. This is also helpful to group them since similar models also typically have a similar name (e.g. GPT). Also makes it so they're next to each other in charts when all models is selected.
Now it's somewhat random which model appears first.
fix ZEN-413

feat: order models, slices, and metrics by name per default

---

frontend/src/lib/components/metadata/Histograms.svelte

fix ZEN-395
The problem here was that we did not load the full histogram data when navigating to the component with a slice, tag, or filter selected.

fix: load full histograms if they have not been loaded always

---

backend/zeno_backend/classes/filter.py
frontend/src/lib/components/popups/FilterEntry.svelte
frontend/src/lib/components/popups/SlicePopup.svelte
frontend/src/lib/util/util.ts
frontend/src/lib/zenoapi/models/Operation.ts

Adds a `NOT_REGEX` Operation to filter predicates, which corresponds to `!~` in Postgres (see [this](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)).

feat: add !~ postgres operation for filter predicates

---

frontend/src/lib/instance-views/schema.json
frontend/src/lib/instance-views/schema.ts

I ran into this use case when I wanted to only visualize the output of a model without any data.

fix: unrequire data in view schema

---

backend/zeno_backend/classes/chart.py
backend/zeno_backend/database/insert.py
backend/zeno_backend/database/select.py
backend/zeno_backend/database/update.py
backend/zeno_backend/processing/filtering.py
backend/zeno_backend/routers/chart.py
frontend/src/lib/components/report/elements/ChartElement.svelte
frontend/src/lib/zenoapi/models/Chart.ts
frontend/src/lib/zenoapi/models/Operation.ts
frontend/src/lib/zenoapi/services/ZenoService.ts
frontend/src/routes/(app)/project/[uuid]/[name]/chart/[chartIndex=integer]/+page.svelte

fix ZEN-414
This disentangles the fetching of chart data from the chart. The reason behind this is that fetching chart data has some failure cases (e.g. a column for a slice filter does not exist anymore) that should not break charts altogether. It should still be possible to change the chart spec. Furthermore, this adds an error message if the chart data could not be loaded.

fix: gracefully fail charts if columns have changed

---

backend/zeno_backend/classes/project.py
backend/zeno_backend/database/insert.py
backend/zeno_backend/database/update.py

Does not automatically overwrite project fields:
`public`, `description`, and `samples_per_page`
when reuploading.
Needs to be merged with: https://github.com/zeno-ml/zeno-client/pull/49

fix: prevent project value overwrite

---

frontend/src/routes/(app)/+layout.svelte
frontend/src/routes/+layout.svelte

The way i had set up view transitions actually made it re-mount all components on every navigation (like the headers), which was significantly slower. Don't think it's worth it, if we want to implement them have to be smarter in the future.

fix: remove view transition

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/home/HomeSearchBar.svelte
frontend/src/lib/typings/index.d.ts
frontend/src/routes/(app)/home/+layout.svelte
frontend/src/routes/(app)/home/+page.svelte
frontend/src/routes/(app)/home/[user]/+page.svelte

fix: show projects only on desktop devices

---

frontend/src/routes/(user)/login/+page.server.ts

It could sometimes happen that we were redirecting to login right after logging in. This has been fixed.

fix: fix bug that redirected to login after logging in

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/instances/ComparisonView.svelte

If output is selected, it does not really make sense to show it since the instance view is shown right below anyway.

fix: don't show ouptut in compare
